<a href="https://colab.research.google.com/github/PaoDeV99/ML_Progetto1_G72/blob/master/p1_g72_gboost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Gradient Boosting Classifier**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


22/06, ore 00:03 <br/>
gbc non accetta in ingresso direttive sul decision tree classifier. Questo vuol dire niente gini (anche se dovrebbe essere impostata di default per i dtc) e niente impostazione sulla max depth (si può ovviare andando ad operare su min_samples_split, ma non sarebbe esattamente la stessa cosa). <br/>
<br/>
Il notebook presenta ancora i risultati di una run di gbc con n_estimators=1000. È stato predisposto per runnare in un ciclo comandato dal numero di stimatori, che varia secondo i valori di estimators. Va ancora impostato per bene il ciclo, prima di farlo runnare. Raccomando pazienza per quando si deciderà di farlo partire: prospetto un tempo di run abbastanza lungo, intorno ai 70 minuti. <br/>
<br/>
Vanno aggiunte delle celle che si occuppino di produrre i plot dell'accuracy al variare del numero di stimatori, così come del tempo di run (ispirati a randomforest). <br/>
<br/>
Finito il lavoro descritto sopra, puoi implementare una feature importance e vedere se e cosa cambia. <br/>
<br/>
Se hai fatto anche quello, perché non tentare la sorte con una random forest classica? O con una logistic regression? A scopo puramente accademico, sarebbe interessante vedere se la logistic regression di oggi riesce a battere il prototipo di gbc e abc.

22/06, ore 22:42 <br/>
Ho inserito la possibilità di collegare il notebook al drive, in modo da non dover ricaricare a mano il txt dei dati ad ogni sessione di lavoro. <br/>
Ho terminato la stesura del ciclo di run di gbc. È impostato per runnare con 100, 200, 500, 800 e 1000 stimatori. Vengono registragti tempo di run, training accuracy, test accuracy e confusion matrix. Ho commentato le celle relative all'impostazione precedente del notebook. <br/>
(Nota a margine: i print effettuati non sono quelli impostati nelle celle. Le modifiche, volte a favorire un'estetica migliore nei print, sono state effettuate solo dopo aver fatto partire il ciclo.)

In [3]:
import numpy as np
import pandas as pd
import time
import warnings
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings('ignore')

In [6]:
df = pd.read_fwf('/content/drive/My Drive/Colab Notebooks/MiniBooNE_PID.txt')

In [7]:
df

36499 93565  Unnamed: 1  ...  Unnamed: 48  Unnamed: 49
0           2.59413    0.468803  ...     0.071769     0.245996
1           3.86388    0.645781  ...     0.333613     0.230621
2           3.38584    1.197140  ...     0.255512     0.180901
3           4.28524    0.510155  ...     0.473081     0.258990
4           5.93662    0.832993  ...     1.924990     0.253893
...             ...         ...  ...          ...          ...
130059      4.80718    1.451020  ...     3.219320     0.299487
130060      5.00527    1.501860  ...     1.778180     0.258058
130061      3.10842    2.178140  ...     0.730342     0.152876
130062      5.44560    1.845700  ...     0.819867     0.210619
130063      4.55062    1.341740  ...     0.742709     0.276477

[130064 rows x 50 columns]

In [8]:
df["signal"]=0
df.iloc[0:36498,50]=1
df.iloc[36499:,50]=0
df

36499 93565  Unnamed: 1  Unnamed: 2  ...  Unnamed: 48  Unnamed: 49  signal
0           2.59413    0.468803     20.6916  ...     0.071769     0.245996       1
1           3.86388    0.645781     18.1375  ...     0.333613     0.230621       1
2           3.38584    1.197140     36.0807  ...     0.255512     0.180901       1
3           4.28524    0.510155    674.2010  ...     0.473081     0.258990       1
4           5.93662    0.832993     59.8796  ...     1.924990     0.253893       1
...             ...         ...         ...  ...          ...          ...     ...
130059      4.80718    1.451020    174.6920  ...     3.219320     0.299487       0
130060      5.00527    1.501860    129.9270  ...     1.778180     0.258058       0
130061      3.10842    2.178140     56.3651  ...     0.730342     0.152876       0
130062      5.44560    1.845700    103.4630  ...     0.819867     0.210619       0
130063      4.55062    1.341740     80.0887  ...     0.742709     0.276477       0

[130064 rows x 51 columns]

In [9]:
#from scipy import stats
#z = np.abs(stats.zscore(df))
#print(z)

In [10]:
#print(np.where(z > 3))

In [11]:
#df_o = df[(z < 3).all(axis=1)]

In [12]:
#df_o

In [13]:
 x_train, x_test, y_train, y_test = train_test_split(
   df.iloc[:,0:50], df["signal"], test_size=0.33, random_state=42)

In [18]:
estimators = [100, 200, 500, 800, 1000]

m=len(estimators)
#n=len(leaf_size_list)

#Allocate Arrays for various quantities
gbc_train_accuracy=np.zeros((m))
gbc_test_accuracy=np.zeros((m))
run_time=np.zeros((m))

for i, nest in enumerate(estimators):
  # Define Gradient Boosting Classifier
  gbc = GradientBoostingClassifier(n_estimators=nest, min_samples_split=2, random_state=0, warm_start=True)
        
  print('n_estimators: %i'%(nest))
        
  start_time = time.time()
  gbc.fit(x_train, y_train)
  run_time[i] = time.time() - start_time    
    
  # check accuracy
  gbc_train_accuracy[i]=gbc.score(x_train,y_train)
  gbc_test_accuracy[i]=gbc.score(x_test,y_test)
  predictions = gbc.predict(x_test)
        
  result = (run_time[i], gbc_train_accuracy[i], gbc_test_accuracy[i])
  print('{0:<15}{1:<15}{2:<15}'.format("time (s)","train score", "test score"))
  print('{0:<15.4f}{1:<15.4f}{2:<15.4f}'.format(*result))
  print('\nConfusion matrix:')
  print(confusion_matrix(y_test, predictions))
  print('\n')

n_estimators: 100
time (s)       train score    test score     
210.8737       0.9326         0.9292         
Confusion matrix:

[[29320  1557]
 [ 1481 10564]]
n_estimators: 200
time (s)       train score    test score     
421.4717       0.9403         0.9356         
Confusion matrix:

[[29402  1475]
 [ 1289 10756]]
n_estimators: 500
time (s)       train score    test score     
1048.0902      0.9501         0.9400         
Confusion matrix:

[[29503  1374]
 [ 1202 10843]]
n_estimators: 800
time (s)       train score    test score     
1606.8446      0.9567         0.9413         
Confusion matrix:

[[29519  1358]
 [ 1161 10884]]
n_estimators: 1000
time (s)       train score    test score     
2090.3456      0.9599         0.9418         
Confusion matrix:

[[29535  1342]
 [ 1154 10891]]


In [19]:
#estimators = [100, 200, 500, 800, 1000]

#for nest in estimators:
  #classifier = GradientBoostingClassifier(
    #DecisionTreeClassifier(criterion='gini',max_depth=45),learning_rate=0.5,
    #the previous line has been excluded because GBC has no option for the base classifier
    #n_estimators = nest,
  #)

  #classifier.fit(x_train,y_train)

In [20]:
#predictions = classifier.predict(x_test)

In [21]:
#confusion_matrix(y_test, predictions)

In [22]:
#classifier.score(x_test,y_test)