<a href="https://colab.research.google.com/github/PaoDeV99/ML_Progetto1_G72/blob/master/Progetto1_Gruppo72.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [ ]:

df = pd.read_fwf('MiniBooNE_PID.txt')

In [ ]:
df

36499 93565  Unnamed: 1  ...  Unnamed: 48  Unnamed: 49
0           2.59413    0.468803  ...     0.071769     0.245996
1           3.86388    0.645781  ...     0.333613     0.230621
2           3.38584    1.197140  ...     0.255512     0.180901
3           4.28524    0.510155  ...     0.473081     0.258990
4           5.93662    0.832993  ...     1.924990     0.253893
...             ...         ...  ...          ...          ...
130059      4.80718    1.451020  ...     3.219320     0.299487
130060      5.00527    1.501860  ...     1.778180     0.258058
130061      3.10842    2.178140  ...     0.730342     0.152876
130062      5.44560    1.845700  ...     0.819867     0.210619
130063      4.55062    1.341740  ...     0.742709     0.276477

[130064 rows x 50 columns]

In [ ]:

df["signal"]=0
df.iloc[0:36498,50]=1
df.iloc[36499:,50]=0
df

36499 93565  Unnamed: 1  Unnamed: 2  ...  Unnamed: 48  Unnamed: 49  signal
0           2.59413    0.468803     20.6916  ...     0.071769     0.245996       1
1           3.86388    0.645781     18.1375  ...     0.333613     0.230621       1
2           3.38584    1.197140     36.0807  ...     0.255512     0.180901       1
3           4.28524    0.510155    674.2010  ...     0.473081     0.258990       1
4           5.93662    0.832993     59.8796  ...     1.924990     0.253893       1
...             ...         ...         ...  ...          ...          ...     ...
130059      4.80718    1.451020    174.6920  ...     3.219320     0.299487       0
130060      5.00527    1.501860    129.9270  ...     1.778180     0.258058       0
130061      3.10842    2.178140     56.3651  ...     0.730342     0.152876       0
130062      5.44560    1.845700    103.4630  ...     0.819867     0.210619       0
130063      4.55062    1.341740     80.0887  ...     0.742709     0.276477       0

[130064 rows x 51 columns]

In [ ]:
from scipy import stats
z = np.abs(stats.zscore(df))
print(z)

[[0.02232761 0.07722394 0.57660199 ... 0.03434471 0.05983779 1.60112227]
 [0.04344796 0.07426118 0.58995464 ... 0.03871271 0.06009488 1.60112227]
 [0.03549649 0.06503096 0.49614893 ... 0.03740985 0.06092627 1.60112227]
 ...
 [0.03088204 0.0486082  0.3901036  ... 0.04533082 0.06139489 0.62456192]
 [0.06975744 0.05417352 0.1438793  ... 0.04682425 0.06042934 0.62456192]
 [0.05487082 0.06261024 0.2660784  ... 0.04553712 0.0593281  0.62456192]]


In [ ]:
print(np.where(z > 3))

(array([     7,     11,     17, ..., 130043, 130043, 130043]), array([15, 15, 15, ..., 47, 48, 49]))


In [ ]:
df_o = df[(z < 3).all(axis=1)]

In [ ]:
df_o

36499 93565  Unnamed: 1  Unnamed: 2  ...  Unnamed: 48  Unnamed: 49  signal
0           2.59413    0.468803     20.6916  ...     0.071769     0.245996       1
1           3.86388    0.645781     18.1375  ...     0.333613     0.230621       1
2           3.38584    1.197140     36.0807  ...     0.255512     0.180901       1
3           4.28524    0.510155    674.2010  ...     0.473081     0.258990       1
4           5.93662    0.832993     59.8796  ...     1.924990     0.253893       1
...             ...         ...         ...  ...          ...          ...     ...
130059      4.80718    1.451020    174.6920  ...     3.219320     0.299487       0
130060      5.00527    1.501860    129.9270  ...     1.778180     0.258058       0
130061      3.10842    2.178140     56.3651  ...     0.730342     0.152876       0
130062      5.44560    1.845700    103.4630  ...     0.819867     0.210619       0
130063      4.55062    1.341740     80.0887  ...     0.742709     0.276477       0

[123480 rows x 51 columns]

In [ ]:
 x_train, x_test, y_train, y_test = train_test_split(
   df_o.iloc[:,0:50], df_o["signal"], test_size=0.33, random_state=42)

In [ ]:
classifier = AdaBoostClassifier(
    DecisionTreeClassifier(criterion='gini',max_depth=45),learning_rate=0.5,
    n_estimators=1000
)

In [ ]:
classifier.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=45,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                         

In [ ]:
predictions = classifier.predict(x_test)

In [ ]:
confusion_matrix(y_test, predictions)

array([[28157,  2303],
       [ 2251,  8038]])

In [ ]:
classifier.score(x_test,y_test)

0.8882426562615033

#**ANN** (bozza, problemi di dimensioni)

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [ ]:
x_train.shape
labels=y_train.iloc[:22]

In [ ]:
labels=keras.utils.to_categorical(labels)

In [ ]:
#definizione modello
#FFNN
model=keras.Sequential([ #FFNN
  keras.layers.Flatten(input_shape=(x_train.shape)), 
  keras.layers.Dense(32, activation='tanh'),
  keras.layers.BatchNormalization(),
  keras.layers.Dropout(0.2),
  keras.layers.Dense(2)        

])

In [ ]:
#compilazione del modello
  #training parametri:
    #Loss Function (categorical_crossentropy)----> misura distanza due distribuz. prob
    #Optimizer (sgd o adam)
    #Metrica 
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 4136550)           0         
_________________________________________________________________
dense_8 (Dense)              (None, 32)                132369632 
_________________________________________________________________
batch_normalization_4 (Batch (None, 32)                128       
_________________________________________________________________
dropout_4 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 66        
Total params: 132,369,826
Trainable params: 132,369,762
Non-trainable params: 64
_________________________________________________________________


In [ ]:
history = model.fit(x_train, y_train,epochs=50,batch_size=128,validation_split=0.2,shuffle=True,verbose=1)

Epoch 1/50


ValueError: ignored